name: cnpj_cpf_helper
description: This library helps with CNPJ and CPF validations. Both of them are a brazilian documentation where CNPJ is a business document and CPF is a person document. 
version: 1.0.8
homepage: https://github.com/evandrofuhr
repository: https://github.com/evandrofuhr/cnpj_cpf_helper

environment:
  sdk: '>=2.8.1 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
